# Generated by Django 4.2.5 on 2023-10-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewdetail',
            name='status',
            field=models.CharField(choices=[('Просмотрено', 'Watched'), ('Не просмотрено', 'Unwatched')], default='Не просмотрено', max_length=20),
        ),
    ]
